#需手动为目标项目导入pagehelper插件
#数据库配置
db:
  driver:
    name: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost:3306/easyJava-demo?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
  username: ####
  password: ####
#是否忽略表前缀，例如：tb_emp --->  emp
ignoreTablePrefix: true
#分页查询pojo的后缀名
pageQueryEntitySuffix: PageQueryDTO
#分页查询的方法命名: 前缀+表名+后缀
pageQueryMethodNamePrefix: select
pageQueryMethodNameSuffix: Page
#文件输出路径
path:
  base: D:/java/idea/AllProjects/workspace-EasyJava/easyJava-demo/src/main
  java: D:/java/idea/AllProjects/workspace-EasyJava/easyJava-demo/src/main/java
  resources: D:/java/idea/AllProjects/workspace-EasyJava/easyJava-demo/src/main/resources
#包名
package:
  base: com.easyjava
  #pojo——（1）entity、（2）dto、（3）vo
  po:
    base: pojo
    entity: entity
    dto: dto
    vo: vo
  #工具包
  utils:
    base: utils
  #全局配置包
  config:
    base: config
  #异常包
  exception:
    base: exception
  #result对象包：Result、PageResult
  result:
    base: result
  #处理器包
  handler:
    base: handler
  #controller
  controller:
    base: controller
  #service
  service:
    base: service
    impl:
      base: impl
      suffix: Impl
  #mapper
  mapper:
    base: mapper
  mapper_xml:
    base: mapper
#日期格式
dateformat:
  date: yyyy-MM-dd
  datetime: yyyy-MM-dd HH:mm:ss
  time: HH:mm:ss


